server {
    listen 443 default_server ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name covan.freightopsconnect.com;

    ssl_certificate /etc/letsencrypt/live/covan.freightopsconnect.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/covan.freightopsconnect.com/privkey.pem;

    location / {
        proxy_pass http://fo-dashboard-covan:80;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
    }
    location /api/ {
        proxy_pass http://fo-api-covan:5000;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
    }
    location /swagger/ {
        proxy_pass http://fo-api-covan:5000/;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
    }
    location /pgadmin4/ {
        allow 76.195.46.56;
        allow 71.81.251.111;
        allow 209.83.83.50;
        deny all;
        proxy_set_header X-Script-Name /pgadmin4;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header Host $host;
        proxy_pass http://pgadmin_container:5050/;
        proxy_redirect off;
    }
}
