version = 4.1.1
archive_dir = /etc/letsencrypt/archive/covan.freightopsconnect.com
cert = /etc/letsencrypt/live/covan.freightopsconnect.com/cert.pem
privkey = /etc/letsencrypt/live/covan.freightopsconnect.com/privkey.pem
chain = /etc/letsencrypt/live/covan.freightopsconnect.com/chain.pem
fullchain = /etc/letsencrypt/live/covan.freightopsconnect.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = a13eb622077863faa834cc93fd22a648
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
